# authentication error messages
authentication.err.validation.authenticator.notfound=Echec d''authentification, authentificateur nomm\u00e9, {0}, introuvable
authentication.err.validation.authenticator.notactive=L'authentificateur n'est pas actif

authentication.err.authentication=Echec d''authentification, nom d''utilisateur ou mot de passe incorrect. Nom d''utilisateur :{0} Raison {1}
authentication.err.connection=Echec de la connexion \u00e0 {0}. Raison {1}
authentication.err.communication=Echec de la communication avec {0}. Raison {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Echec de la connexion, h\u00f4te ldap {0} inconnu
authentication.err.connection.ldap.user.notfound=Utilisateur LDAP {0} introuvable
authentication.err.connection.ldap.manager.notfound=Utilisateur gestionnaire LDAP {0} introuvable
authentication.err.connection.ldap.search=Impossible de rechercher dans LDAP. Raison {0}

# PASSTHRU
authentication.err.connection.passthru.server=Impossible d'ouvrir une session sur le serveur interm\u00e9diaire
authentication.err.passthru.token.unsupported=Type de jeton d'authentification non pris en charge
authentication.err.passthru.guest.notenabled=Connexions invit\u00e9s d\u00e9sactiv\u00e9es
authentication.err.passthru.user.disabled=Compte d\u00e9sactiv\u00e9
authentication.err.passthru.user.notfound=Utilisateur interm\u00e9diaire {0} introuvable

# Authentication Diagnostic Steps
authentication.step.ldap.validation=Validation de requ\u00eate
authentication.step.ldap.connecting=Connexion au serveur LDAP {0} 
authentication.step.ldap.connected=Connect\u00e9 au serveur LDAP {0} avec le principal\u00a0: {1}
authentication.step.ldap.lookup=Recherche utilisateur test userId :{0} avec la requ\u00eate\u00a0: {1}
authentication.step.ldap.lookedup=Recherch\u00e9 utilisateur test userId\u00a0:{0}, trouv\u00e9 nom unique\u00a0:{1}
authentication.step.ldap.format.user=Format nom utilisateur sp\u00e9cifi\u00e9, userNameFormat\u00a0:{2} Format utilisateur userId :{0} pour cr\u00e9er un nom unique\u00a0:{1}
authentication.step.ldap.authentication=Authentifier userId :{0}


# Sync Summary message 
synchronization.summary.status={0} utilisateur(s) et {1} groupe(s) trait\u00e9(s)


# Error messages
authentication.ldap.validation.authenticator.notfound=Authentificateur introuvable

# Synchronization Diagnostic Steps
synchronization.step.users={0} utilisateurs trouv\u00e9s
synchronization.step.groups={0} groupes trouv\u00e9s
synchronization.step.users.lastsynced=Utilisateurs derni\u00e8rement synchronis\u00e9s {0} avec succ\u00e8s
synchronization.step.groups.lastsynced=Groupes derni\u00e8rement synchronis\u00e9s {0} avec succ\u00e8s

synchronization.err.ldap.search=Erreur lors de la recherche dans LDAP. Raison\u00a0: {0}
synchronization.err.ldap.get.user.id.missing=L''utilisateur ne dispose pas du nom unique de l''attribut identifiant utilisateur = {0}, attributeName = {1})
synchronization.err.ldap.get.group.id.missing=Le groupe ne dispose pas du nom unique de l''attribut identifiant groupe = {0}, attributeName = {1})

synchronization.err.ldap.search.base.invalid=Recherche non valide applicable \u00e0 la raison {0}\u00a0: {1}

synchronization.err.ldap.group.member.missing.exception=Impossible de r\u00e9soudre le membre du groupe {0} avec le nom unique\u00a0: {1}, raison {2})\u00a0;
synchronization.err.ldap.group.member.missing=Impossible de r\u00e9soudre le membre du groupe {0} avec le nom unique\u00a0: {1})\u00a0;



       



